### ISSUE TITLE
AAD is not fixed in Austria

### ISSUE THREAD

**Issue by arno82** [schopenhauer/sage#5]
The AAD is not fixed to 3000112233445566778899AABBCCDDEEFF in Austria for Sagemcom T210 smart meters.
Normally the value will be delivered together with the main key.
AAD is named Global Authentication Key (GAK).

Thus this value should be configurable.

**Comment by schopenhauer** [comment]
Thanks for letting me know. This has been fixed in [970a32d](https://github.com/schopenhauer/sage/commit/970a32d83f9753ef749c92a74e135563eff43b62).

**Comment by arno82** [comment]
Thanks, but unfortunately it still doesn't work for me. But the reason could also be a different one. Although everything is working in the smarty_dsmr_proxy, so my setup is basically OK.
What I get all the time, even if I fix the AAD in the sourcecode:
10:50:42.770Z DEBUG app: Received data 14: 45e5b31f054588243fe780dae4f9c29682ec7253 (truncated) / size: 66
10:50:42.770Z  WARN app: Unknown data length (33), ignoring data
10:50:42.791Z DEBUG app: Received data 15: 1862f0ac714593b4b59af9b4be3ee9d1d02bcf6d (truncated) / size: 134
10:50:42.791Z  WARN app: Unknown data length (67), ignoring data

So something is strange here. Always the double of the expected data length is received
